/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    projekte: Projekte;
    leistungen: Leistungen;
    testimonials: Testimonial;
    jobs: Job;
    faqs: Faq;
    aerzte: Aerzte;
    termine: Termine;
    anamnese: Anamnese;
    media: Media;
    users: User;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    projekte: ProjekteSelect<false> | ProjekteSelect<true>;
    leistungen: LeistungenSelect<false> | LeistungenSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    aerzte: AerzteSelect<false> | AerzteSelect<true>;
    termine: TermineSelect<false> | TermineSelect<true>;
    anamnese: AnamneseSelect<false> | AnamneseSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    settings: Setting;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Referenzprojekte. Reihenfolge steuert die Bento-Kacheln auf der Startseite und Vor/Zurück auf den Detailseiten.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projekte".
 */
export interface Projekte {
  id: number;
  title: string;
  /**
   * z. B. „Holzhaus · Neubau", „Dachstuhl"
   */
  tag: string;
  location: string;
  year: string;
  hero: number | Media;
  /**
   * Erscheint im Hero und als Meta-Description.
   */
  lead: string;
  /**
   * Die dunkle Faktenleiste (idealerweise 4 Einträge).
   */
  facts?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  aufgabe: string;
  loesung: string;
  ergebnis: string;
  /**
   * Bilder für die Galerie mit Lightbox.
   */
  gallery?: (number | Media)[] | null;
  /**
   * Nur befüllen, wenn ein Vergleichs-Regler gezeigt werden soll. Beide Bilder nötig.
   */
  beforeAfter?: {
    before?: (number | null) | Media;
    after?: (number | null) | Media;
    caption?: string | null;
  };
  /**
   * Layout im Bento-Raster der Startseite.
   */
  featuredSize?: ('big' | 'tall' | 'wide') | null;
  sortOrder?: number | null;
  /**
   * Wird automatisch aus dem Titel erzeugt – nur ändern, wenn nötig.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Kurze Bildbeschreibung für Screenreader und SEO.
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Die Leistungskacheln in der Hero — jede mit eigener Detailseite unter /leistungen/<slug>.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leistungen".
 */
export interface Leistungen {
  id: number;
  title: string;
  /**
   * Erscheint als Teaser (Kachel/Liste) und als Meta-Description der Detailseite.
   */
  description: string;
  icon: 'stethoscope' | 'heart' | 'shield' | 'child' | 'lab' | 'housecall';
  /**
   * Ein bis zwei Sätze unter der Überschrift der Detailseite.
   */
  lead?: string | null;
  /**
   * Der Hauptabsatz: worum geht es bei dieser Leistung.
   */
  intro?: string | null;
  /**
   * Stichpunkt-Liste der konkreten Leistungen.
   */
  leistungspunkte?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optionale Schritte, die den Ablauf erklären.
   */
  ablauf?:
    | {
        titel: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  faq?:
    | {
        frage: string;
        antwort: string;
        id?: string | null;
      }[]
    | null;
  sortOrder?: number | null;
  /**
   * Wird automatisch aus dem Titel erzeugt – nur ändern, wenn nötig.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Kundenstimmen im Abschnitt „Was am Ende zählt".
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  author: string;
  project: string;
  /**
   * z. B. „FH" für Familie Huber.
   */
  initials: string;
  rating?: number | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Offene Stellen im Karriere-Abschnitt.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: number;
  title: string;
  /**
   * z. B. „Vollzeit · Landshut".
   */
  type: string;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Häufige Fragen im FAQ-Abschnitt.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Die Ärzte der Praxis – Profilkarten und buchbare Sprechzeiten.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aerzte".
 */
export interface Aerzte {
  id: number;
  /**
   * z. B. „Dr. med.", optional.
   */
  titel?: string | null;
  name: string;
  /**
   * Erscheint unter dem Namen, z. B. „Fachärztin für Innere Medizin".
   */
  fachrichtung: string;
  foto?: (number | null) | Media;
  /**
   * Ein bis zwei Sätze zur Person – erscheint auf der Profilkarte.
   */
  vita?: string | null;
  /**
   * Nur aktive Ärzte erscheinen im Buchungstool.
   */
  aktiv?: boolean | null;
  /**
   * Länge eines Slots im Buchungsraster.
   */
  slotDauerMin: number;
  /**
   * Wöchentliche Blöcke. Lücken zwischen Blöcken (z. B. Mittagspause) sind automatisch nicht buchbar.
   */
  sprechzeiten?:
    | {
        wochentag: '1' | '2' | '3' | '4' | '5' | '6' | '7';
        von: string;
        bis: string;
        id?: string | null;
      }[]
    | null;
  /**
   * In diesen Zeiträumen werden keine Slots angeboten.
   */
  abwesenheiten?:
    | {
        von: string;
        bis: string;
        grund?: string | null;
        id?: string | null;
      }[]
    | null;
  sortOrder?: number | null;
  /**
   * Wird automatisch aus dem Titel erzeugt – nur ändern, wenn nötig.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Gebuchte Termine. Enthält Patientendaten – streng vertraulich.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "termine".
 */
export interface Termine {
  id: number;
  arzt: number | Aerzte;
  /**
   * Geschlossene Kategorie – kein Freitext (Datenschutz).
   */
  terminart: 'kontrolle' | 'akut' | 'vorsorge' | 'erstgespraech' | 'befundbesprechung';
  start: string;
  ende?: string | null;
  patientName: string;
  patientGeburtsdatum?: string | null;
  patientEmail: string;
  patientTelefon?: string | null;
  versicherung?: ('gesetzlich' | 'privat' | 'selbstzahler') | null;
  istNeupatient?: boolean | null;
  /**
   * Nur bei Neupatienten, sofern ausgefüllt.
   */
  anamnese?: (number | null) | Anamnese;
  status: 'ausstehend' | 'bestaetigt' | 'abgesagt' | 'wahrgenommen' | 'nicht_erschienen';
  /**
   * Nur mit ausdrücklicher Einwilligung bei der Buchung (Art. 9 DSGVO).
   */
  erinnerungErwuenscht?: boolean | null;
  erinnerungGesendet?: boolean | null;
  /**
   * Terminkalender ist keine Behandlungsdoku – kurz nach dem Termin löschen.
   */
  loeschdatum?: string | null;
  /**
   * Nur praxisintern – nicht vom Patienten ausgefüllt.
   */
  notizPraxis?: string | null;
  verifyToken?: string | null;
  verifyExpiresAt?: string | null;
  manageToken?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Verschlüsselte Anamnesebögen. Inhalt nur mit dem Praxis-Schlüssel lesbar.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "anamnese".
 */
export interface Anamnese {
  id: number;
  eingegangenAm?: string | null;
  ciphertext?: string | null;
  encryptedKey?: string | null;
  iv?: string | null;
  algo?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'projekte';
        value: number | Projekte;
      } | null)
    | ({
        relationTo: 'leistungen';
        value: number | Leistungen;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'jobs';
        value: number | Job;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'aerzte';
        value: number | Aerzte;
      } | null)
    | ({
        relationTo: 'termine';
        value: number | Termine;
      } | null)
    | ({
        relationTo: 'anamnese';
        value: number | Anamnese;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projekte_select".
 */
export interface ProjekteSelect<T extends boolean = true> {
  title?: T;
  tag?: T;
  location?: T;
  year?: T;
  hero?: T;
  lead?: T;
  facts?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  aufgabe?: T;
  loesung?: T;
  ergebnis?: T;
  gallery?: T;
  beforeAfter?:
    | T
    | {
        before?: T;
        after?: T;
        caption?: T;
      };
  featuredSize?: T;
  sortOrder?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leistungen_select".
 */
export interface LeistungenSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  icon?: T;
  lead?: T;
  intro?: T;
  leistungspunkte?:
    | T
    | {
        text?: T;
        id?: T;
      };
  ablauf?:
    | T
    | {
        titel?: T;
        text?: T;
        id?: T;
      };
  faq?:
    | T
    | {
        frage?: T;
        antwort?: T;
        id?: T;
      };
  sortOrder?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  author?: T;
  project?: T;
  initials?: T;
  rating?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aerzte_select".
 */
export interface AerzteSelect<T extends boolean = true> {
  titel?: T;
  name?: T;
  fachrichtung?: T;
  foto?: T;
  vita?: T;
  aktiv?: T;
  slotDauerMin?: T;
  sprechzeiten?:
    | T
    | {
        wochentag?: T;
        von?: T;
        bis?: T;
        id?: T;
      };
  abwesenheiten?:
    | T
    | {
        von?: T;
        bis?: T;
        grund?: T;
        id?: T;
      };
  sortOrder?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "termine_select".
 */
export interface TermineSelect<T extends boolean = true> {
  arzt?: T;
  terminart?: T;
  start?: T;
  ende?: T;
  patientName?: T;
  patientGeburtsdatum?: T;
  patientEmail?: T;
  patientTelefon?: T;
  versicherung?: T;
  istNeupatient?: T;
  anamnese?: T;
  status?: T;
  erinnerungErwuenscht?: T;
  erinnerungGesendet?: T;
  loeschdatum?: T;
  notizPraxis?: T;
  verifyToken?: T;
  verifyExpiresAt?: T;
  manageToken?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "anamnese_select".
 */
export interface AnamneseSelect<T extends boolean = true> {
  eingegangenAm?: T;
  ciphertext?: T;
  encryptedKey?: T;
  iv?: T;
  algo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Branding, Kontaktdaten, Startseiten-Texte und Rechtstexte – an einer Stelle.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  brandName: string;
  brandSuffix: string;
  legalName: string;
  region: string;
  tagline?: string | null;
  phoneDisplay: string;
  phoneHref: string;
  email: string;
  addressStreet?: string | null;
  addressCity?: string | null;
  /**
   * Je Zeile ein Tag bzw. Tagesbereich und die zugehörige Zeit.
   */
  oeffnungszeiten?:
    | {
        tag: string;
        zeit: string;
        id?: string | null;
      }[]
    | null;
  heroBadge?: string | null;
  heroHeadingLine1?: string | null;
  heroHeadingPrefix?: string | null;
  heroHeadingAccent?: string | null;
  heroLead?: string | null;
  heroStats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  marquee?:
    | {
        word: string;
        id?: string | null;
      }[]
    | null;
  stats?:
    | {
        count: number;
        /**
         * z. B. „+", „%", „ m³"
         */
        suffix?: string | null;
        label: string;
        id?: string | null;
      }[]
    | null;
  careerHeadingPrefix?: string | null;
  careerHeadingAccent?: string | null;
  careerText?: string | null;
  buchungIntro?: string | null;
  /**
   * Öffentlicher Schlüssel der Praxis (Base64-SPKI). Nur damit werden Anamnesebögen verschlüsselt. Der PRIVATE Schlüssel gehört ausschließlich auf die Praxis-Geräte – niemals hier oder auf den Server.
   */
  anamnesePublicKey?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  brandName?: T;
  brandSuffix?: T;
  legalName?: T;
  region?: T;
  tagline?: T;
  phoneDisplay?: T;
  phoneHref?: T;
  email?: T;
  addressStreet?: T;
  addressCity?: T;
  oeffnungszeiten?:
    | T
    | {
        tag?: T;
        zeit?: T;
        id?: T;
      };
  heroBadge?: T;
  heroHeadingLine1?: T;
  heroHeadingPrefix?: T;
  heroHeadingAccent?: T;
  heroLead?: T;
  heroStats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  marquee?:
    | T
    | {
        word?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        count?: T;
        suffix?: T;
        label?: T;
        id?: T;
      };
  careerHeadingPrefix?: T;
  careerHeadingAccent?: T;
  careerText?: T;
  buchungIntro?: T;
  anamnesePublicKey?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}